/*
* Copyright 2026 eQ-3 AG - All Rights Reserved.
* 
* Licensed under the HMSL 2 (the "License"). You may not use
* this file except in compliance with the License.  You can obtain a copy
* in the file HMSL.txt in the source distribution.
*/

Coprocessor Device Path = /dev/mxs_auart_raw.0
Log Level = 3
Log Identifier = multimac
Log Destination = Syslog
HmIP Cmdline Pattern = */crRFD*
Bidcos Cmdline Pattern = *rfd -c*
Transparent Cmdline Pattern = *update*
Bidcos Exe Pattern = */bin/rfd
Default Subsystem = HmIP
Loop Master Device = /dev/eq3loop
Loop Slave Device Bidcos = mmd_bidcos
Loop Slave Device HmIP = ttyS0
Traffic Log = 0
Traffic Log Directory = /var/log
